[project]
name = "heteromark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "smacv2",
]

[tool.uv.sources]
smacv2 = { git = "https://github.com/oxwhirl/smacv2.git" }
